### ISSUE TITLE
Autotrace webhook for cron jobs

### ISSUE THREAD

**Issue by shamilpatel25** [instana/instana-autotrace-webhook#3]
I setup autotrace webhook for my kubernetes cluster to pickup all of our node.js applications. We have a few cronjobs running and I noticed that cronjobs arent automatically applied with the label instana-autotrace-applied = true. 

Is this something that will be added in the future?

**Comment by basti1302** [comment]
Sorry for not getting back to you earlier. I just replied on the support ticket where you brought that up. Just for transparency, let me repeat here: This is currently not supported and there are no plans around cronjobs. If you are interested, please open a feature request at https://support.instana.com/hc/en-us/requests/new for cronjob support in the autotrace webhook.
